name: CI

on:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                node-version-file: ".nvmrc"
            - run: npm ci --ignore-scripts
            - run: npm test
